version: 1
accounts:
- name: alice
  coins:
  - 20000rbs
  - 200000000stake
- name: bob
  coins:
  - 10000rbs
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5rbs
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
send_enabled:
  - denom: rbs
    enabled: true
