version: 1
accounts:
- name: alice
  coins:
  - 100rbs
  - 200000000stake
- name: bob
  coins:
  - 100rbs
  - 100000000stake
- name: admin
  coins:
    - 100rbs
- name: dev
  coins:
  - 100rbs
  mnemonic: lucky valid identify sun village gloom random purpose draft lamp whale build egg clog cook stage velvet trumpet judge behind collect electric hospital gap
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5rbs
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
send_enabled:
  - denom: rbs
    enabled: true
#genesis: TODO would be nice being able to set genesis accounts here
#  app_state:
#    therealblock:
#      adminAccounts:
#        - "realblock18njy4mmunlt2dkw283l0x754d4yv6tgdv6nsxc"
